// Типы судов и должности для локализации
// Эти массивы содержат КЛЮЧИ для перевода, а не сами названия

// Ключи типов судов для локализации
export const vesselTypeKeys = [
  'accommodationVessel',
  'anchorHandlingTug',
  'anchorHandlingVessel',
  'barge',
  'bulkCarrier',
  'cableLayer',
  'chemicalTanker',
  'containerShip',
  'craneVessel',
  'crewBoat',
  'cruiseShip',
  'divingSupportVessel',
  'dredger',
  'drillShip',
  'ferry',
  'fishingVessel',
  'fpso',
  'fso',
  'generalCargo',
  'heavyLiftVessel',
  'highSpeedCraft',
  'hospitalShip',
  'icebreaker',
  'jackUpRig',
  'landingCraft',
  'livestockCarrier',
  'lngCarrier',
  'lpgCarrier',
  'mooringVessel',
  'multipurposeVessel',
  'navalVessel',
  'ocv',
  'offshoreDrillingRig',
  'offshoreSupply',
  'passengerShip',
  'pipeLayer',
  'platformSupply',
  'platformSupport',
  'reefer',
  'rehabilitationVessel',
  'researchVessel',
  'roro',
  'sailingVessel',
  'semiSubmersibleRig',
  'standbyVessel',
  'surveyVessel',
  'tanker',
  'trainingShip',
  'tug',
  'tugBoat',
  'tugSupplyVessel',
  'walkToWorkVessel',
  'yacht',
  'other'
];

// Английские названия (сохраняются в БД для совместимости)
export const vesselTypes = [
  'Accommodation Vessel',
  'Anchor Handling Tug',
  'Anchor Handling Vessel',
  'Barge',
  'Bulk Carrier',
  'Cable Layer',
  'Chemical Tanker',
  'Container Ship',
  'Crane Vessel',
  'Crew Boat',
  'Cruise Ship',
  'Diving Support Vessel',
  'Dredger',
  'Drill Ship',
  'Ferry',
  'Fishing Vessel',
  'FPSO',
  'FSO',
  'General Cargo',
  'Heavy Lift Vessel',
  'High Speed Craft',
  'Hospital Ship',
  'Icebreaker',
  'Jack Up Rig',
  'Landing Craft',
  'Livestock Carrier',
  'LNG Carrier',
  'LPG Carrier',
  'Mooring Vessel',
  'Multipurpose Vessel',
  'Naval Vessel',
  'Offshore Construction Vessel',
  'Offshore Drilling Rig',
  'Offshore Supply',
  'Passenger Ship',
  'Pipe Layer',
  'Platform Supply',
  'Platform Support',
  'Reefer',
  'Rehabilitation Vessel',
  'Research Vessel',
  'RoRo',
  'Sailing Vessel',
  'Semi Submersible Rig',
  'Standby Vessel',
  'Survey Vessel',
  'Tanker',
  'Training Ship',
  'Tug',
  'Tug Boat',
  'Tug Supply Vessel',
  'Walk to Work Vessel',
  'Yacht',
  'Other'
];

// Маппинг: строгое соответствие элементов массива vesselTypes ключам vesselTypeKeys
export const vesselTypeToKey: { [key: string]: string } = {
  'Accommodation Vessel': 'accommodationVessel',
  'Anchor Handling Tug': 'anchorHandlingTug',
  'Anchor Handling Vessel': 'anchorHandlingVessel',
  'Barge': 'barge',
  'Bulk Carrier': 'bulkCarrier',
  'Cable Layer': 'cableLayer',
  'Chemical Tanker': 'chemicalTanker',
  'Container Ship': 'containerShip',
  'Crane Vessel': 'craneVessel',
  'Crew Boat': 'crewBoat',
  'Cruise Ship': 'cruiseShip',
  'Diving Support Vessel': 'divingSupportVessel',
  'Dredger': 'dredger',
  'Drill Ship': 'drillShip',
  'Ferry': 'ferry',
  'Fishing Vessel': 'fishingVessel',
  'FPSO': 'fpso',
  'FSO': 'fso',
  'General Cargo': 'generalCargo',
  'Heavy Lift Vessel': 'heavyLiftVessel',
  'High Speed Craft': 'highSpeedCraft',
  'Hospital Ship': 'hospitalShip',
  'Icebreaker': 'icebreaker',
  'Jack Up Rig': 'jackUpRig',
  'Landing Craft': 'landingCraft',
  'Livestock Carrier': 'livestockCarrier',
  'LNG Carrier': 'lngCarrier',
  'LPG Carrier': 'lpgCarrier',
  'Mooring Vessel': 'mooringVessel',
  'Multipurpose Vessel': 'multipurposeVessel',
  'Naval Vessel': 'navalVessel',
  'Offshore Construction Vessel': 'ocv',
  'Offshore Drilling Rig': 'offshoreDrillingRig',
  'Offshore Supply': 'offshoreSupply',
  'Passenger Ship': 'passengerShip',
  'Pipe Layer': 'pipeLayer',
  'Platform Supply': 'platformSupply',
  'Platform Support': 'platformSupport',
  'Reefer': 'reefer',
  'Rehabilitation Vessel': 'rehabilitationVessel',
  'Research Vessel': 'researchVessel',
  'RoRo': 'roro',
  'Sailing Vessel': 'sailingVessel',
  'Semi Submersible Rig': 'semiSubmersibleRig',
  'Standby Vessel': 'standbyVessel',
  'Survey Vessel': 'surveyVessel',
  'Tanker': 'tanker',
  'Training Ship': 'trainingShip',
  'Tug': 'tug',
  'Tug Boat': 'tugBoat',
  'Tug Supply Vessel': 'tugSupplyVessel',
  'Walk to Work Vessel': 'walkToWorkVessel',
  'Yacht': 'yacht',
  'Other': 'other'
};

// Должности (для SeaService и Personal)
export const positions = [
  'Master',
  'Master SDPO',
  'Master DPO',
  'Deputy Master',
  'Chief Officer',
  'Chief Officer SDPO',
  'Chief Officer DPO',
  '1st Officer SDPO',
  'SDPO',
  'DPO',
  '1st Officer DPO',
  '1st Officer',
  '2nd Officer',
  '2nd Officer SDPO',
  '2nd Officer DPO',
  '3rd Officer',
  'Deck Cadet',
  'Engine Cadet',
  'Chief Engineer',
  '2nd Engineer',
  '3rd Engineer',
  '4th Engineer',
  'ETO',
  'Bosun',
  'AB Crane Operator',
  'AB',
  'OS',
  'Oiler',
  'Wiper',
  'Fitter',
  'Chief Steward',
  'Chief Cook',
  'Cook',
  'Steward',
  'Laundryman',
  'Medic',
  'Radio Officer',
  'Purser',
  'IT Officer',
  'Pumpman',
  'Crane Operator',
  'Deck Engineer',
  'Rigger',
  'Security Officer',
  'Safety Officer',
  'Other'
];

// Функции для форматирования дат
export const formatDate = (dateString: string): string => {
  if (!dateString) return '-';
  const date = new Date(dateString);
  if (isNaN(date.getTime())) return dateString;
  
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  
  return `${day}-${month}-${year}`;
};

export const formatDateForFilename = (date: Date): string => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  
  return `${year}${month}${day}`;
};