// Regenerates utils/flags.ts from the country-flag-icons SVGs.
//
// Emoji flags (🇬🇧) are not an option: Windows ships no glyphs for regional-indicator
// pairs, so on the desktop build every flag rendered as a blank box. These are inlined
// as data URIs — no runtime dependency, no network, works offline.
//
//   node scripts/gen-flags.js
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'node_modules', 'country-flag-icons', '3x2');
const OUT = path.join(__dirname, '..', 'utils', 'flags.ts');

const LANG_TO_COUNTRY = {
  en: 'GB', uk: 'UA', pl: 'PL', de: 'DE', es: 'ES',
  fr: 'FR', ru: 'RU', tl: 'PH', zh: 'CN', hi: 'IN',
};

const entries = Object.entries(LANG_TO_COUNTRY).map(([lang, country]) => {
  const svg = fs.readFileSync(path.join(SRC, `${country}.svg`), 'utf8').replace(/\n\s*/g, '');
  const uri = `data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}`;
  return `  ${lang}: '${uri}',`;
});

const out = `// GENERATED by scripts/gen-flags.js — do not edit by hand.
//
// Flag images for the language picker, inlined as data URIs. Emoji flags cannot be used:
// Windows ships no glyphs for them, so they render as empty boxes in the desktop build.
// Source: country-flag-icons (MIT).
export const FLAGS: Record<string, string> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(OUT, out);
console.log(`gen-flags: wrote ${entries.length} flags to utils/flags.ts (${(out.length / 1024).toFixed(1)} KB)`);
